/*
 * hwpe_ctrl_target.sv
 * Francesco Conti <f.conti@unibo.it>
 *
 * Copyright (C) 2014-2025 ETH Zurich, University of Bologna
 * Copyright and related rights are licensed under the Solderpad Hardware
 * License, Version 0.51 (the "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of the License at
 * http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
 * or agreed to in writing, software, hardware and materials distributed under
 * this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

/**
 * The **hwpe_ctrl_target** module implements the control-side target (slave)
 * port of an HWPE, exposing a `hwpe_ctrl_intf_periph` interface used by an
 * external core to program a memory-mapped register file. It supersedes the
 * deprecated `hwpe_ctrl_slave` module: rather than hard-coding a register
 * file, it relies on a register interface that is generated out of a
 * SystemRDL description. The `hwpe-ctrl` repository ships a reference
 * `hwpe_ctrl_regif_example.rdl` description and a `rdl.sh` helper script
 * that invokes PeakRDL to generate the register interface; HWPEs must
 * internalize this description and modify its contents to match their own
 * set of *job-independent* and *job-dependent* registers (without altering
 * the mandatory registers, see below).
 *
 * Then, the `hwpe_ctrl_target` can be integrated by 1) overriding the
 * parametric types `hwpe_ctrl_regif_in_t`, `hwpe_ctrl_regif_out_t`,
 * `hwpe_ctrl_job_indep_t`, `hwpe_ctrl_job_dep_t` with the ones produced by
 * PeakRDL; 2) plugging the register-interface (cpuif) signals to the
 * SystemRDL-generated register interface block; 3) plugging `hwif_in` and
 * `hwif_out` to the same block.
 *
 * The module also implements an internal job queue (of depth *NB_CONTEXT*)
 * that allows new jobs to be enqueued via the `ACQUIRE` / `COMMIT_TRIGGER`
 * mandatory registers while the HWPE is still busy executing the previous
 * one. The mandatory registers (always present in the SystemRDL description)
 * are summarized below.
 *
 * .. tabularcolumns:: |l|l|J|
 * .. _hwpe_ctrl_target_params:
 * .. table:: **hwpe_ctrl_target** design-time parameters.
 *
 *   +---------------------------+--------------+----------------------------------------------------------------------------+
 *   | **Name**                  | **Default**  | **Description**                                                            |
 *   +---------------------------+--------------+----------------------------------------------------------------------------+
 *   | *NB_CONTEXT*              | 2            | Depth of the job queue (number of jobs that can be enqueued concurrently). |
 *   +---------------------------+--------------+----------------------------------------------------------------------------+
 *   | *NB_CLEAR_CYCLES*         | 3            | Duration in clock cycles of a soft-clear pulse generated by `SOFT_CLEAR`.  |
 *   +---------------------------+--------------+----------------------------------------------------------------------------+
 *   | *ID_WIDTH*                | 2            | Width of the transaction ID on the peripheral interface.                   |
 *   +---------------------------+--------------+----------------------------------------------------------------------------+
 *   | *ADDR_WIDTH*              | 16           | Width of the address on the register-file interface.                      |
 *   +---------------------------+--------------+----------------------------------------------------------------------------+
 *   | *hwpe_ctrl_regif_in_t*    | *logic*      | Type of `hwif_in` (must be overridden with the PeakRDL-generated type).    |
 *   +---------------------------+--------------+----------------------------------------------------------------------------+
 *   | *hwpe_ctrl_regif_out_t*   | *logic*      | Type of `hwif_out` (must be overridden with the PeakRDL-generated type).   |
 *   +---------------------------+--------------+----------------------------------------------------------------------------+
 *   | *hwpe_ctrl_job_indep_t*   | *logic*      | Type of the job-independent register bundle (must be overridden).          |
 *   +---------------------------+--------------+----------------------------------------------------------------------------+
 *   | *hwpe_ctrl_job_dep_t*     | *logic*      | Type of the job-dependent register bundle (must be overridden).            |
 *   +---------------------------+--------------+----------------------------------------------------------------------------+
 *
 * .. tabularcolumns:: |l|J|
 * .. _hwpe_ctrl_target_regs:
 * .. table:: **hwpe_ctrl_target** mandatory registers.
 *
 *   +--------------------+------------------------------------------------------------------------------------------------+
 *   | **Register**       | **Description**                                                                                |
 *   +--------------------+------------------------------------------------------------------------------------------------+
 *   | *ACQUIRE*          | Read to acquire a new job ID. Returns ``0xffff_ffff`` if the job queue is full, or             |
 *   |                    | ``0xffff_fffe`` if a job is already being acquired but has not been committed yet.             |
 *   +--------------------+------------------------------------------------------------------------------------------------+
 *   | *COMMIT_TRIGGER*   | Writing 0 to bit 1 commits the currently acquired job to the queue; writing 0 to bit 0         |
 *   |                    | triggers execution of the next job in the queue (asserts `job_trigger_o`).                     |
 *   +--------------------+------------------------------------------------------------------------------------------------+
 *   | *SOFT_CLEAR*       | Writing 0 to bit 0 clears the register file; writing 0 to bit 1 clears the engine state       |
 *   |                    | (`clear_o`). Each clear is held high for *NB_CLEAR_CYCLES* cycles.                             |
 *   +--------------------+------------------------------------------------------------------------------------------------+
 *   | *STATUS*           | Exposes the externally-provided `job_status_i` 32-bit status word.                             |
 *   +--------------------+------------------------------------------------------------------------------------------------+
 *   | *RUNNING_JOB*      | Exposes the current running job ID.                                                            |
 *   +--------------------+------------------------------------------------------------------------------------------------+
 *
 */

module hwpe_ctrl_target
  import hwpe_ctrl_package::*;
#(
  parameter int unsigned NB_CONTEXT      = 2,
  parameter int unsigned NB_CLEAR_CYCLES = 3,
  parameter int unsigned ID_WIDTH        = 2,
  parameter int unsigned ADDR_WIDTH      = 16,
  parameter int unsigned AUTOTRIGGER_WAIT_CYCLES = 3,
  parameter type hwpe_ctrl_regif_in_t  = logic, // must be overridden!
  parameter type hwpe_ctrl_regif_out_t = logic, // must be overridden!
  parameter type hwpe_ctrl_job_indep_t = logic, // must be overridden!
  parameter type hwpe_ctrl_job_dep_t   = logic  // must be overridden!
)
(
  input  logic                 clk_i,
  input  logic                 rst_ni,
  output logic                 clear_o,

  // peripheral interconnect side
  hwpe_ctrl_intf_periph.slave  target,

  // job triggering completion & status
  output logic                 job_trigger_o,
  input  logic                 job_done_i,
  input  logic [31:0]          job_status_i,

  // job-independent registers
  output hwpe_ctrl_job_indep_t job_indep_regs_o,

  // job-dependent registers
  output logic                 job_dep_regs_valid_o,
  output hwpe_ctrl_job_dep_t   job_dep_regs_o,

  // cpuif interface to target SystemRDL-generated register interface (PeakRDL "passthrough")
  output logic                 target_cpuif_req_o,
  output logic                 target_cpuif_req_is_wr_o,
  output logic [31:0]          target_cpuif_addr_o,
  output logic [31:0]          target_cpuif_wr_data_o,
  output logic [31:0]          target_cpuif_wr_biten_o,
  input  logic                 target_cpuif_req_stall_wr_i,
  input  logic                 target_cpuif_req_stall_rd_i,
  input  logic                 target_cpuif_rd_ack_i,
  input  logic                 target_cpuif_rd_err_i,
  input  logic [31:0]          target_cpuif_rd_data_i,
  input  logic                 target_cpuif_wr_ack_i,
  input  logic                 target_cpuif_wr_err_i,

  // wrap -> register interface signals
  output hwpe_ctrl_regif_in_t  hwif_in,

  // register interface -> wrap signals
  input  hwpe_ctrl_regif_out_t hwif_out
);

  // Adapt the peripheral interconnect (hwpe_ctrl_intf_periph) to the combinational PeakRDL
  // "passthrough" register-interface (cpuif) protocol. The cpuif accepts a request and returns
  // read data combinationally in the same cycle, back-pressuring via the stall outputs.
  // periph -> cpuif request (combinational). The address is word-aligned (low two bits masked)
  // because the passthrough cpuif decodes exact word addresses and, unlike the OBI cpuif, does
  // not mask the byte offset itself.
  assign target_cpuif_req_o       =  target.req;
  assign target_cpuif_req_is_wr_o = ~target.wen;
  assign target_cpuif_addr_o      = {{(32-ADDR_WIDTH){1'b0}} , target.add[ADDR_WIDTH-1:2], 2'b00};
  assign target_cpuif_wr_data_o   =  target.data;

  // expand the 4-bit byte-enable into the 32-bit bit-enable expected by the cpuif
  always_comb begin
    for(int unsigned i=0; i<4; i++) begin
      target_cpuif_wr_biten_o[i*8 +: 8] = {8{target.be[i]}};
    end
  end

  // combinational grant: accept unless the register interface stalls the current access.
  // HWPE registers never stall (single-cycle); cpuif multi-cycle (rd_ack-gated) accesses
  // are not supported by this adapter.
  logic target_cpuif_stall;
  assign target_cpuif_stall = target.req & (target.wen ? target_cpuif_req_stall_rd_i
                                                       : target_cpuif_req_stall_wr_i);
  assign target.gnt = ~target_cpuif_stall;

  // register the read response one cycle after a granted request
  logic                target_r_valid_q;
  logic [31:0]         target_r_data_q;
  logic [ID_WIDTH-1:0] target_r_id_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if(~rst_ni) begin
      target_r_valid_q <= 1'b0;
      target_r_data_q  <= '0;
      target_r_id_q    <= '0;
    end
    else begin
      target_r_valid_q <= target.req & target.gnt;
      target_r_data_q  <= target_cpuif_rd_data_i;
      target_r_id_q    <= target.id;
    end
  end
  assign target.r_valid = target_r_valid_q;
  assign target.r_data  = target_r_data_q;
  assign target.r_id    = target_r_id_q;

  // unused cpuif status signals (no error/ack channel on the periph interface)
  logic unused_cpuif_ack_err;
  assign unused_cpuif_ack_err = target_cpuif_rd_ack_i & target_cpuif_rd_err_i &
                                target_cpuif_wr_ack_i & target_cpuif_wr_err_i;

  // error codes for job offload
  localparam logic [31:0] HWPE_CTRL_JOB_QUEUE_FULL_ERR_CODE = 32'hffff_ffff;
  localparam logic [31:0] HWPE_CTRL_JOB_ACQUIRED_ERR_CODE   = 32'hffff_fffe;

  // state of job offload procedure
  typedef enum logic { IDLE, ACQUIRE } job_offload_state_t;
  job_offload_state_t job_offload_state_d, job_offload_state_q;

  // current and next acquired job ID
  logic [7:0] job_acquired_id_d, job_acquired_id_q;

  // current and next running job ID
  logic [7:0] job_running_id_d, job_running_id_q;

  // job running flag: set (0->1) when job_trigger_o fires, cleared (1->0) by job_done_early_q
  logic job_running_q;

  // delayed job done (job_done_i delayed by AUTOTRIGGER_WAIT_CYCLES cycles;
  // AUTOTRIGGER_WAIT_CYCLES=1 reproduces the original single-register delay)
  logic job_done_q;
  logic [AUTOTRIGGER_WAIT_CYCLES-1:0] job_done_sr_q;

  // job commit signal
  logic job_commit;

  // job queue control signals
  logic job_fifo_full, job_fifo_empty;

  // internal clear signals
  logic                       soft_clear_regfile_d, soft_clear_state_d;
  logic [NB_CLEAR_CYCLES-1:0] soft_clear_regfile_q, soft_clear_state_q;
  logic                       soft_clear_regfile_en, soft_clear_state_en;

  // Registered job_done, delayed by AUTOTRIGGER_WAIT_CYCLES cycles
  always_ff @(posedge clk_i or negedge rst_ni)
  begin
    if(~rst_ni) begin
      job_done_sr_q <= '0;
    end
    else if(|soft_clear_regfile_q) begin
      job_done_sr_q <= '0;
    end
    else begin
      job_done_sr_q[0] <= job_done_i;
      for(int i=1; i<AUTOTRIGGER_WAIT_CYCLES; i++) begin
        job_done_sr_q[i] <= job_done_sr_q[i-1];
      end
    end
  end
  assign job_done_q = job_done_sr_q[AUTOTRIGGER_WAIT_CYCLES-1];

  // job_done_i delayed by AUTOTRIGGER_WAIT_CYCLES-1 cycles
  logic job_done_early_q;
  generate
    if (AUTOTRIGGER_WAIT_CYCLES > 1) begin : gen_job_done_early_geq2_gen
      assign job_done_early_q = job_done_sr_q[AUTOTRIGGER_WAIT_CYCLES-2];
    end
    else begin : gen_job_done_early_eq1_gen
      assign job_done_early_q = job_done_i;
    end
  endgenerate

  // Registered software-access strobes for the write-command registers.
  // PeakRDL exposes `.value` from the registered field storage (updated one cycle after a
  // write) but `.swacc` as a combinational strobe asserted during the write cycle.
  logic commit_trigger_swacc_q, soft_clear_swacc_q;
  always_ff @(posedge clk_i or negedge rst_ni)
  begin
    if(~rst_ni) begin
      commit_trigger_swacc_q <= 1'b0;
      soft_clear_swacc_q     <= 1'b0;
    end
    else begin
      commit_trigger_swacc_q <= hwif_out.hwpe_ctrl.commit_trigger.commit_trigger.swacc;
      soft_clear_swacc_q     <= hwif_out.hwpe_ctrl.soft_clear.soft_clear.swacc;
    end
  end

  // SOFT_CLEAR register:
  // clear regfile if SOFT_CLEAR[0] is 0, clear state if SOFT_CLEAR[1] is 0
  assign soft_clear_regfile_d = soft_clear_swacc_q & ~hwif_out.hwpe_ctrl.soft_clear.soft_clear.value[0];
  assign soft_clear_state_d   = soft_clear_swacc_q & ~hwif_out.hwpe_ctrl.soft_clear.soft_clear.value[1];

  // generate clear enables
  assign soft_clear_regfile_en = soft_clear_regfile_d | (|soft_clear_regfile_q);
  assign soft_clear_state_en   = soft_clear_state_d   | (|soft_clear_state_q);

  // activate clear for NB_CLEAR_CYCLES cycles in case of a SOFT_CLEAR write
  always_ff @(posedge clk_i or negedge rst_ni)
  begin
    if(~rst_ni) begin
      soft_clear_regfile_q <= '0;
    end
    else if(soft_clear_regfile_en) begin
      soft_clear_regfile_q[0] <= soft_clear_regfile_d;
      for(int i=1; i<NB_CLEAR_CYCLES; i++) begin
        soft_clear_regfile_q[i] <= soft_clear_regfile_q[i-1];
      end
    end
  end
  always_ff @(posedge clk_i or negedge rst_ni)
  begin
    if(~rst_ni) begin
      soft_clear_state_q <= '0;
    end
    else if(soft_clear_state_en) begin
      soft_clear_state_q[0] <= soft_clear_state_d;
      for(int i=1; i<NB_CLEAR_CYCLES; i++) begin
        soft_clear_state_q[i] <= soft_clear_state_q[i-1];
      end
    end
  end

  // propagate the soft_clear_state everywhere
  assign clear_o = |soft_clear_state_q;

  // COMMIT_TRIGGER register:
  // Commit a job in the job queue if COMMIT_TRIGGER[1] is 1'b0. Trigger the job queue execution if COMMIT_TRIGGER[0] is 1'b0.
  assign job_commit    =  commit_trigger_swacc_q & ~hwif_out.hwpe_ctrl.commit_trigger.commit_trigger.value[1];
  assign job_trigger_o = (commit_trigger_swacc_q & ~hwif_out.hwpe_ctrl.commit_trigger.commit_trigger.value[0] & ~job_running_q) | // trigger when a TRIGGER arrives and no job is running
                         (~hwif_out.hwpe_ctrl.autotrigger.autotrigger_n.value & job_done_q & ~job_fifo_empty); // trigger with autotrigger if active and there are pending jobs

  // ACQUIRE register:
  // 1. if in ACQUIRE state, respond to any new reads with error code (-2)
  // 2. if job_fifo_full, respond with error code (-1)
  // 3. else, return the next job ID
  assign hwif_in.hwpe_ctrl.acquire.acquire.next = job_offload_state_q == ACQUIRE ? HWPE_CTRL_JOB_ACQUIRED_ERR_CODE   :
                                                  job_fifo_full                  ? HWPE_CTRL_JOB_QUEUE_FULL_ERR_CODE :
                                                                                   { 24'h0 , job_acquired_id_q };

  always_ff @(posedge clk_i or negedge rst_ni)
  begin
    if(~rst_ni) begin
      job_acquired_id_q <= '0;
    end
    else if(|soft_clear_regfile_q) begin
      job_acquired_id_q <= '0;
    end
    else if((job_offload_state_q == IDLE) & ~job_fifo_full & hwif_out.hwpe_ctrl.acquire.acquire.swacc) begin
      job_acquired_id_q <= job_acquired_id_d;
    end
  end
  assign job_acquired_id_d = job_acquired_id_q + 1;

  always_ff @(posedge clk_i or negedge rst_ni)
  begin
    if(~rst_ni) begin
      job_running_id_q <= '0;
    end
    else if(|soft_clear_regfile_q) begin
      job_running_id_q <= '0;
    end
    else if(job_done_i) begin
      job_running_id_q <= job_running_id_d;
    end
  end
  assign job_running_id_d = job_running_id_q + 1;

  always_ff @(posedge clk_i or negedge rst_ni)
  begin
    if(~rst_ni) begin
      job_running_q <= 1'b0;
    end
    else if(|soft_clear_regfile_q) begin
      job_running_q <= 1'b0;
    end
    else if(job_trigger_o) begin
      job_running_q <= 1'b1;
    end
    else if(job_done_early_q) begin
      job_running_q <= 1'b0;
    end
  end

  // enable state change on ACQUIRE / COMMIT_TRIGGER register access
  logic job_offload_state_en;
  assign job_offload_state_en = hwif_out.hwpe_ctrl.acquire.acquire.swacc | job_commit;
  
  // update state (cleared together with register file)
  assign job_offload_state_d = hwif_out.hwpe_ctrl.acquire.acquire.swacc & ~job_fifo_full ? ACQUIRE :
                               job_commit                                                ? IDLE    :
                                                                                           job_offload_state_q;
  always_ff @(posedge clk_i or negedge rst_ni)
  begin
    if(~rst_ni) begin
      job_offload_state_q <= IDLE;
    end
    else if(|soft_clear_regfile_q) begin
      job_offload_state_q <= IDLE;
    end
    else if(job_offload_state_en) begin
      job_offload_state_q <= job_offload_state_d;
    end
  end

  // STATUS register:
  // propagate status defined externally
  assign hwif_in.hwpe_ctrl.status.status0.next = job_status_i;

  // RUNNING_JOB register:
  // return the current job ID
  assign hwif_in.hwpe_ctrl.running_job.running_job.next = job_running_id_q;

  // queue for incoming jobs
  fifo_v3 #(
    .FALL_THROUGH ( 0                   ),
    .DEPTH        ( NB_CONTEXT          ),
    .dtype        ( hwpe_ctrl_job_dep_t )
  ) i_job_fifo (
    .clk_i      ( clk_i                 ),
    .rst_ni     ( rst_ni                ),
    .flush_i    ( |soft_clear_regfile_q ),
    .testmode_i ( '0                    ),
    .full_o     ( job_fifo_full         ),
    .empty_o    ( job_fifo_empty        ),
    .usage_o    (                       ),
    .data_i     ( hwif_out.hwpe_job_dep ),
    .push_i     ( job_commit            ),
    .data_o     ( job_dep_regs_o        ),
    .pop_i      ( job_done_i            )
  );
  assign job_dep_regs_valid_o = ~job_fifo_empty;

  // job-independent registers
  assign job_indep_regs_o = hwif_out.hwpe_job_indep;

endmodule // hwpe_ctrl_target
